version: '3.7'
services:
  spring:
    container_name: citybike-app
    build: .
    restart: "no"
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/citybike-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=M3ZBuCdLudQAN3
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  postgres-db:
    container_name: citybike-db
    image: postgres
    restart: "no"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST: postgres-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: M3ZBuCdLudQAN3
      POSTGRES_DB: citybike-db